### ISSUE TITLE
Ajustar permissões das models

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#107]
Ajustar permissões de cada model do backend conforme a tabela abaixo:

|Model|Admin|Doador|Receptor|
|---|---|---|---|
|Doador|Gerenciar* todos doadores|Gerenciar* a própria conta|-/-|
|Evento|Gerenciar* todos eventos|Gerenciar* se for o dono|Apenas visualizar os eventos|
|Categoria|Gerenciar* todas categorias|Ver categorias|Ver categorias|

*Gerenciar = CRUD

**Tarefas**
- [x] Completar permissões do doador
- [x] Completar permissões do evento
- [x] Completar permissões das categorias

**Critérios de aceitação**
- [x] Completar todas permissões

**Comment by LucasPLopes** [comment]
@brunaalmeidasantos 
Adicionado e configura os requisitos para evento e categorias

**Comment by LucasPLopes** [comment]
@brunaalmeidasantos 
As configurações de gerenciamentos para o doador foram adicionadas no front exibindo apenas os evento do id do usuário logado

**Comment by roginaldosemog** [comment]
Os ajustes foram concluídos e já foram mesclados com a develop de cada repositório.
