### ISSUE TITLE
Montar apresentação da R2

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#111]
Para que haja uma visão geral do que foi feito no projeto, e necessário que se monte uma apresentação.

**Tópicos**
- [x] Apresentar resumo do FoodCare
- [ ] Apresentar evidências da utilização da metodologia ágil (XP, dailys, quadro de conhecimento...)
- [ ] Apresentar o software desenvolvido

**Critérios de aceitação**
- [x] Link para a apresentação na issue

**Comment by geraldovictor** [comment]
https://docs.google.com/presentation/d/1LbdBbFUzmuNOiEcpnXX67QTlzVySio_GCGqc_ytFsTQ/edit#slide=id.g75aaa8ee0f_4_4
