### ISSUE TITLE
Iniciar projetos

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#15]
Iniciar projetos de cada tecnologia que será utilizada no FoodCare.

**Tarefas**
- [x] Iniciar Django REST API
- [x] Iniciar Angular em novo repositório

**Critérios de aceitação**
- [x] Passar nas tarefas descritas acima

**Comment by roginaldosemog** [comment]
Repositório para o WebApp Angular criado: https://github.com/fga-eps-mds/2019.2-FoodCare-WebApp

**Comment by WillAllmeida** [comment]
As tarefas propostas nessa issue foram cumpridas.
