### ISSUE TITLE
Adicionar Licença

### ISSUE THREAD

**Issue by WillAllmeida** [fga-eps-mds/2019.2-FoodCare#36]
Adicionar licença GPL 3.0 aos repositórios do projeto

**Tarefas**
- [x] Adicionar arquivo com licença no repositório do backend
- [x] Adicionar arquivo com licença no repositório do frontend

**Critérios de aceitação**
- [x] Passar nas tarefas acima

**Comment by roginaldosemog** [comment]
As tarefas foram concluidas.
