### ISSUE TITLE
Criar README

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2019.2-FoodCare#39]
Readme é um dos artefatos mais importante de projetos de software

**Tarefas**
- [x] Olhar template de bons readmes
- [x] Aplicar as boas práticas no readme do projeto

**Critérios de aceitação**
- [x] Qualquer pessoa é capaz de entender o projeto, subir a aplicação e contribuir com o projeto

**Comment by roginaldosemog** [comment]
Readme atualizado conforme solicitado, tanto no [repo da API](https://github.com/fga-eps-mds/2019.2-FoodCare), quanto no [repo da WebApp](https://github.com/fga-eps-mds/2019.2-FoodCare-WebApp).
