### ISSUE TITLE
Criar Home

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#40]
Desenvolver o HTML da página inicial (home) do projeto, para apresentação do projeto.

**Requisitos**
- [x] Instalar Angular Material
- [x] Header
- [x] Menu Sanduíche
- [x] Seção Introdutória
- [x] Seção "Sobre o FoodCare"
- [x] Footer

**Critérios de aceitação**
- [ ] Ter todas tarefas acima desenvolvidas
- [ ] Passar no Travis

**Comment by geraldovictor** [comment]
Nav-bar gerada, conteúdo adicionado,  fontes adicionadas, trabalhando agora pra deixar o conteúdo responsivo.

**Comment by geraldovictor** [comment]
Faltando conectar o front com back, precisando de ajuda.

**Comment by roginaldosemog** [comment]
> Faltando conectar o front com back, precisando de ajuda.

Não há a necessidade de conectar o front com o back, já que a funcionalidade envolve apenas a página inicial, que não utiliza dados da api

**Comment by roginaldosemog** [comment]
@geraldovictor ainda falta algo para fechar a US?
