### ISSUE TITLE
Criar Pipeline de Deploy Contínuo

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#45]
Adicionar Pipeline de Deploy Contínuo, para que os todos estejam cientes do processo que será seguido no projeto.

**Tarefas**
- [x] Criar documento

**Critérios de aceitação**
- [x] Link do documento na issue

**Comment by WillAllmeida** [comment]
https://fga-eps-mds.github.io/2019.2-FoodCare/devops/pipeline/

**Comment by roginaldosemog** [comment]
Veja o [documento de Pipeline de Deploy Contínuo](https://fga-eps-mds.github.io/2019.2-FoodCare/devops/pipeline/).
