### ISSUE TITLE
Criar Plano de Gerenciamento de Riscos

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#46]
Para que a gerencia se planeje melhor e tente prever dificuldades que possam acontecer durante o projeto, deve-se criar o Plano de Gerenciamento de Riscos.

**Tarefas**
- [x] Criar documento

**Critérios de aceitação**
- [x] Link do documento na issue

**Comment by saraivinha97** [comment]
[Para acessar o documento de gerenciamento de risco click aqui](https://github.com/fga-eps-mds/2019.2-FoodCare/blob/docs/docs/projeto/plano_risco.md)

**Comment by roginaldosemog** [comment]
Done
