### ISSUE TITLE
Criar Documento de Ferramentas

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#47]
Para que a equipe possa se familiarizar com as ferramentas que serão utilizadas, deve-se criar o Plano de Gerenciamento de Riscos.

**Tarefas**
- [ ] Criar documento

**Critérios de aceitação**
- [ ] Link do documento na issue

**Comment by saraivinha97** [comment]
[Para acessar o documento de ferramnetas click aqui](https://github.com/fga-eps-mds/2019.2-FoodCare/commit/f72abf4cfcbdd01696f3adbff83ecbf214cb2f11)

**Comment by roginaldosemog** [comment]
@saraivinha97 da próxima vez muda pra review, pra eu poder revisar ;)
