### ISSUE TITLE
Criar Plano de Gerenciamento de Qualidade

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#54]
Para que a equipe possa se familiarizar com as ações referentes à qualidade adotadas no projeto, deve-se criar o Plano de Gerenciamento de Qualidade.

**Tarefas**
- [x] Criar documento

**Critérios de aceitação**
- [x] Link do documento na issue

**Comment by WillAllmeida** [comment]
https://fga-eps-mds.github.io/2019.2-FoodCare/devops/plano_qualidade/

**Comment by roginaldosemog** [comment]
Os critérios de aceitação foram cumpridos.
