### ISSUE TITLE
Criar Formulário de Contato

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#61]
Criar formulário de contato, na página inicial, que envie uma mensagem para o email do projeto FoodCare.

**Requisitos**
- [x] Formulário de contato na homepage
- [x] Enviar email de contato para foodcare.unb@gmail.com

**Critérios de aceitação**
- [x] Finalizar os requisitos acima

**Comment by LucasPLopes** [comment]
@brunaalmeidasantos API para recebimento criada e funcionando

**Comment by roginaldosemog** [comment]
A feature atendeu às especificações.
