### ISSUE TITLE
Conectar Evento ao Doador

### ISSUE THREAD

**Issue by saraivinha97** [fga-eps-mds/2019.2-FoodCare#85]
Fazer com que o evento ao ser criado, mostre qual o doador que o criou.

**Tarefas**
- [x] Modificar a model de evento no Django
- [x] Ter o nome do doador que criou o evento no front

**Critérios de aceitação**
- [x] Ter todas tarefas acima desenvolvidas
- [x] Passar no Travis
- [x] Subir cobertura de testes

**Comment by roginaldosemog** [comment]
O pull request foi aceito, e os critérios foram aprovados
