### ISSUE TITLE
Gerenciar Perfil de Doadores

### ISSUE THREAD

**Issue by saraivinha97** [fga-eps-mds/2019.2-FoodCare#86]
Permitir com que o usuário gerencie as informações pessoais da conta.

**Tarefas**
- [x] Editar dados da conta.
- [x] Deletar conta.

**Critérios de aceitação**
- [x] As tarefas acima serem desenvolvidas.
- [x] Passar pelo Travis.
- [x] Subir cobertura de teste.

**Comment by roginaldosemog** [comment]
Os critérios foram aceitos e os pull requests foram aprovados.
