### ISSUE TITLE
Dojo: Testes Unitários no Angular

### ISSUE THREAD

**Issue by saraivinha97** [fga-eps-mds/2019.2-FoodCare#87]
Para que a equipe de MDS possa aprender mais sobre testes unitários em Angular.

**Data e horário:** 08/11/19 às 16h
**Local:** FGA - Sala I1

**Tarefas**
- [x] Ensinar sobre Testes Unitários em Angular

**Critérios de Aceitação**
- [ ] Elaboração e link da ata da reunião

**Comment by roginaldosemog** [comment]
O dojo foi realizado com sucesso.

A ata de reunião, com mais detalhes, pode ser acessada [aqui](https://github.com/fga-eps-mds/2019.2-FoodCare/blob/docs/docs/projeto/reunioes/reuniao_06.md).
