### ISSUE TITLE
Configurar Localização

### ISSUE THREAD

**Issue by roginaldosemog** [fga-eps-mds/2019.2-FoodCare#94]
Configurar sistema de geolocalização, para calcular distância entre o doador e o receptor.

**Requisitos**
- [x] Model de evento com os atributos de longitude e latitude, no backend
- [x] Receber, com a permissão do usuário, a localização atual dele, no frontend
- [x] Armazenar, com a permissão do doador, a localização do evento
- [x] Calcular a distância entre o receptor e o evento
- [x] Ordenar eventos por menor distância

**Critérios de aceitação**
- [x] Finalizar os requisitos acima

**Comment by LucasPLopes** [comment]
* Criada função de calculo de distância(back) e teste
* Função de captura da localização(front)
* Atualizada model com Latitude e Longitude

@RafaellaJunqueira

**Comment by roginaldosemog** [comment]
Os critérios foram aceitos e os pull requests foram aprovados.
